from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from .symbol_export import gams_symbol_ranges


def _symbol_lines(instance: Dict[str, Any]) -> list[str]:
    """Build GDXXRW symbol specification lines."""
    rows = gams_symbol_ranges(instance)
    lines = [
        "* GDXXRW symbol import specification generated by snapgen",
        "* This file is intended to be used from the instance root folder.",
    ]
    for row in rows:
        if row["kind"] == "set":
            lines.append(f"set={row['name']} rng={row['range']} rDim=1")
        else:
            lines.append(f"par={row['name']} rng={row['range']} rDim={row['rdim']} cDim=0")
    return lines


def _import_gms(instance_id: str, *, root_mode: bool) -> str:
    """Create an import script."""
    if root_mode:
        header = "* Canonical script: run from the instance root folder."
    else:
        header = "* Convenience copy: also run this from the instance root folder, not from gams/."
    return f"""$title Import SNAP instance {instance_id} from Excel to GDX
{header}
* Required files in the current folder:
*   instance.xlsx
*   gdxxrw_symbols.txt
*
* Recommended command from the instance folder:
*   gams import_to_gdx.gms

$call gdxxrw "instance.xlsx" output="instance.gdx" @gdxxrw_symbols.txt
$ifE errorLevel<>0 $abort GDXXRW failed while creating instance.gdx

$log Created instance.gdx from instance.xlsx
"""


def _declarations(*, root_mode: bool) -> str:
    gdx_path = "instance.gdx" if root_mode else "../instance.gdx"
    lines = [
        "* GAMS declarations for SNAP instance symbols",
        "Sets",
        "    I    student groups",
        "    D    courses",
        "    W    wards",
        "    H    hospitals",
        "    S    shifts",
        "    T    days in a week",
        "    K    weeks in the semester;",
        "",
        "Parameters",
        "    mem(I)",
        "    semester(I)",
        "    Du(D)",
        "    O(D)",
        "    PW(D)",
        "    Dur(D,W)",
        "    weeks(D,W)",
        "    Cap(D,W,H)",
        "    ne(D,W)",
        "    nee(D,W)",
        "    nt(W)",
        "    B(W,H)",
        "    Mea(D,W)",
        "    Comm(I,D)",
        "    Com(I,D,W)",
        "    Eb(D,W,H)",
        "    Av(I,T,K)",
        "    Avb(W,H,T,K);",
        "",
        f"$gdxin {gdx_path}",
        "$load I D W H S T K mem semester Du O PW Dur weeks Cap ne nee nt B Mea Comm Com Eb Av Avb",
        "$gdxin",
    ]
    return "\n".join(lines) + "\n"


def write_gams_import_files(root: str | Path, instance: Dict[str, Any]) -> None:
    """Write GAMS/GDXXRW helper files for a generated instance.

    v1.6.0 writes canonical helper files in the instance root folder and mirrored
    documentation/copies in the gams/ subfolder. This fixes path-resolution issues
    in older GAMS/GDXXRW versions where @gdxxrw_symbols.txt is resolved relative to
    the current working directory, not necessarily relative to the .gms file.
    """
    gams_dir = Path(root)
    gams_dir.mkdir(parents=True, exist_ok=True)
    instance_root = gams_dir.parent

    instance_id = instance.get("metadata", {}).get("instance_id", "instance")
    symbol_text = "\n".join(_symbol_lines(instance)) + "\n"

    # Canonical files in the instance root. Run: gams import_to_gdx.gms
    (instance_root / "gdxxrw_symbols.txt").write_text(symbol_text, encoding="utf-8")
    (instance_root / "import_to_gdx.gms").write_text(_import_gms(instance_id, root_mode=True), encoding="utf-8")
    (instance_root / "declarations_and_load.inc").write_text(_declarations(root_mode=True), encoding="utf-8")

    # Mirror files in gams/ for organization/reference. The import script is still
    # designed to be launched from the instance root to keep paths unambiguous.
    (gams_dir / "gdxxrw_symbols.txt").write_text(symbol_text, encoding="utf-8")
    (gams_dir / "import_to_gdx.gms").write_text(_import_gms(instance_id, root_mode=False), encoding="utf-8")
    (gams_dir / "declarations_and_load.inc").write_text(_declarations(root_mode=False), encoding="utf-8")

    readme = """GAMS/GDXXRW helper files

Canonical usage, from the instance root folder:
    gams import_to_gdx.gms

This creates:
    instance.gdx

Important:
- In v1.6.0, import_to_gdx.gms and gdxxrw_symbols.txt are written in the instance root folder.
- This avoids path problems in older GAMS/GDXXRW versions where @gdxxrw_symbols.txt is resolved from the current working directory.
- The gams/ folder contains mirrored helper files and documentation, but the safest command is to run the root-level import_to_gdx.gms from the instance root.

Files in the instance root:
- import_to_gdx.gms: canonical GAMS script to create instance.gdx.
- gdxxrw_symbols.txt: symbol-to-range mapping for GDXXRW.
- declarations_and_load.inc: optional GAMS declarations and $load statements.

The workbook uses long-form sheets:
- set_* sheets contain one set element per row.
- par_* and tab_* sheets contain domain columns followed by a numeric value column.
"""
    (gams_dir / "README_gams.txt").write_text(readme, encoding="utf-8")
    (instance_root / "README_gams.txt").write_text(readme, encoding="utf-8")
